Update run

diff --git a/etc/service/networkmanager/run b/etc/service/networkmanager/run
--- a/etc/service/networkmanager/run
+++ b/etc/service/networkmanager/run
@@ -1,21 +1,25 @@
 #!/bin/sh
-
-# lksys starts services concurrently, so wait for D-Bus first
+# NetworkManager service for lksystem
 wait_for_socket() {
   timeout=30
   while ! test -S "$1" && ! test -S "$2"; do
     timeout=$((timeout - 1))
     if test "$timeout" -eq 0; then
+      echo "Timeout waiting for D-Bus socket" >&2
       exit 1
     fi
     sleep 1
   done
 }
 
-wait_for_socket /run/dbus/system_bus_socket /var/run/dbus/system_bus_socket "D-Bus"
-for networkmanager in /usr/sbin/NetworkManager /usr/bin/NetworkManager; do
-  if test -x "$networkmanager"; then
-    exec "$networkmanager" --no-daemon
+wait_for_socket /run/dbus/system_bus_socket /var/run/dbus/system_bus_socket
+
+# Searching valid NetworkManager binary
+for bin in /usr/bin/NetworkManager /usr/sbin/NetworkManager; do
+  if [ -x "$bin" ]; then
+    exec "$bin" --no-daemon
   fi
 done
-exec NetworkManager --no-daemon
+
+echo "NetworkManager binary not found!" >&2
+exit 1
